### ISSUE TITLE
Async problem with response.

### ISSUE THREAD

**Issue by akademy** [jgkaplan/gemini-server#1]
Hi,

Am I right in thinking that this async code should still work under gemini? It's based on your example but with just setTimeout (representing some asynchronous call).

```
app.on('/input', (req, res) => {
	if(req.query){
		setTimeout( function() {
			res.data('you typed ' + req.query);
		}, 500)
	}else{
		res.input('type something');
	}
});
```

I'm getting a "Page not found" call after inputting some text. I believe it is incorrectly closing the call when the handler exits.

I'm using the GemiNaut browser.

Thanks.

**Comment by jgkaplan** [comment]
You're right; that should work. I'll try to push a fix soon
