### ISSUE TITLE
Cannot import audio files

### ISSUE THREAD

**Issue by ghost** [jgkaplan/gemini-server#10]
Tried using res.file for audio files, does not work. Could you possibly add support for this?

**Comment by jgkaplan** [comment]
What happens when you try to do it, and what do you expect/want to happen?

**Comment by ghost** [comment]
It just shows a play button, and plays nothing when I click on it (also shows no error in console). I have only tested this with .ogg files as this is what other people use on their capsules. 
I want to be able to play audio files stored on my server on my gemini capsule.

**Comment by jgkaplan** [comment]
alright I'll look into it

**Comment by jgkaplan** [comment]
Should be fixed now.

**Comment by ghost** [comment]
Issue is still occurring with audio files.
```TypeScript
// Test
app.on('/music', (req: any, res: any) => {
    res.file(`${__dirname}/static/audio/music.mp3`);
})
```
This issue occurs with both mp3 and ogg files which I did test. No errors were produced in terminal.

**Comment by jgkaplan** [comment]
Did you update to the latest version of the library?

**Comment by ghost** [comment]
My bad. That was the issue.

**Comment by jgkaplan** [comment]
👍
