### ISSUE TITLE
Status is 51 even if page is valid

### ISSUE THREAD

**Issue by ghost** [jgkaplan/gemini-server#12]

**Comment by ghost** [comment]
Full response: `Response { _status: 51, _meta: 'Not Found.', _body: null }`

**Comment by jgkaplan** [comment]
Can you post the code you're using?

**Comment by floofywoofles** [comment]
https://github.com/floofywoofles/gemini-home-capsule
I do not know which specific piece of code you need. This is everything being used in my project.

**Comment by ghost** [comment]
```typescript
// Middleware to track status and path
app.use('*', (req: any, res: any, next: any) => {
    const status: number = res.getStatus();
    console.log({ path: req.path, status: status })

    next();
})

```

**Comment by jgkaplan** [comment]
By default, the status is always 51 until you change it by calling res.data, res.input, res.file, res.redirect, or res.certify. Calling any of these updates the status. You can also change the status manually by calling res.status.

**Comment by ghost** [comment]
This causes issues though especially if you want to create a custom "404" page whenever status is 51, and nothing in Request or Response would allow me to implement this myself to determine if a route is valid or not unless I manually stored each route in an array. 
Is there any possible way to detect if its a valid route beforehand instead of waiting for Response to determine this?

**Comment by jgkaplan** [comment]
To write a custom 404 page, you could have this as the last route:
```
app.on('*', (req, res) => {
    res.file('404.gemini');
});
```

This would work as a catch-all route at the end of the processing chain.

**Comment by floofywoofles** [comment]
res.file,res.data, and res.redirect do not work in middleware.

**Comment by jgkaplan** [comment]
sorry, meant to use a handler rather than middleware. Use `app.on('*', ...)` rather than `app.use('*',...)`
