### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by puyoxyz** [jgkaplan/gemini-server#14]
types pls? (so can use it in typescript projects) 👉👈

**Comment by jgkaplan** [comment]
I added type definitions in another branch. I'm not really sure how to test them. If you pull that branch and try them, and they compile and work successfully (or if you have any advice on how to make sure they work), I'll merge them into the main branch and push them to the npm repo

**Comment by puyoxyz** [comment]
index.d.ts doesn't export Request and Response
![image](https://user-images.githubusercontent.com/15311104/154833510-12adc991-3602-4bb3-9803-bd1f600c6963.png)

and I need to use those types here
![image](https://user-images.githubusercontent.com/15311104/154833525-79beb045-c42e-4980-a71a-be1195fe924e.png)

**Comment by jgkaplan** [comment]
I've tried updating the types branch. Let me know if this works?

**Comment by nailujx86** [comment]
Looking good and so far everything seems to be covered.
