### ISSUE TITLE
What port is this listening on?

### ISSUE THREAD

**Issue by lodenrogue** [jgkaplan/gemini-server#3]
I tried the gemini port 1965 and nothing is responding from there. Also tried port 80 but no luck either.

After installing the certs and spinning up the service how do I hit the endpoints? I have a gemini browser I can test with.

**Comment by jgkaplan** [comment]
It is port 1965 by default (though you can change that). Are you making a request to gemini://<url>:1965 ?

**Comment by lodenrogue** [comment]
Sorry total newb when it comes to gemini. I thought it was localhost:1965. I just tried:

```
gemini://:1965 
```
And I got the following error on my browser

```
Failed to connect to the 
server: hostname does not
verify: x509: certificate
is not valid for any
names, but wanted to
match .
```

**Comment by lodenrogue** [comment]
If it helps here's my Dockerfile

```
FROM alpine:3.13.5

RUN apk add --update nodejs nodejs-npm

RUN apk add --update openssl

COPY ./ /app

WORKDIR /app

RUN openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'

RUN npm install

ENTRYPOINT ["node", "app.js"] 
```

And app.js is the same as the code in the REAME.

**Comment by jgkaplan** [comment]
did you try going to gemini://localhost:1965 ?

**Comment by jgkaplan** [comment]
also, if you're using docker, have you exposed the port 1965?

**Comment by jgkaplan** [comment]
> Sorry total newb when it comes to gemini. I thought it was localhost:1965. I just tried:

also honestly same

**Comment by lodenrogue** [comment]
I got it to work. Docker was exposing ports but the key was going to:

```
gemini://localhost:1965
```

**Comment by jgkaplan** [comment]
nice

**Comment by lodenrogue** [comment]
I'm curios why just localhost didn't work. I thought the default port was 1965. Are pages on gemini usually served on a different port?

**Comment by jgkaplan** [comment]
Port 1965 is the default, in my understanding. Maybe the browser you were using didn't automatically request that port though?
