### ISSUE TITLE
Any way to get a path variable?

### ISSUE THREAD

**Issue by lodenrogue** [jgkaplan/gemini-server#4]
I have a path that looks like this: /weather/:location

How do I grab the :location value?

**Comment by lodenrogue** [comment]
req.params is coming back as undefined. Here's my full code:

```javascript
app.on('/weather/:location',(req, res) => {
    console.log(req.params);
    res.data('done');
});
```

**Comment by jgkaplan** [comment]
I don't think there's currently support for that. I'll add that in

**Comment by jgkaplan** [comment]
alright, hopefully this has been added. I really need a test suite for this :P

**Comment by lodenrogue** [comment]
Thank you I'll check it out

**Comment by lodenrogue** [comment]
Is this automatically pushed up to npm?

**Comment by jgkaplan** [comment]
ah whoops I forgot about that. I'll push to npm

**Comment by lodenrogue** [comment]
Thank you

**Comment by lodenrogue** [comment]
@jgkaplan Seems to be working for me. Thank you for the quick response!
